import os
import requests
from typing import Dict
from urllib.parse import urlparse


def build_markdown(review: Dict) -> str:
    """
    Convert Crew review JSON into GitHub-flavored Markdown.
    """

    severity_map = {
        "high": "🔴 HIGH",
        "medium": "🟡 MEDIUM",
        "low": "🟢 LOW"
    }

    severity = severity_map.get(review.get("severity", "low"), "⚪ UNKNOWN")

    md = f"""## 🤖 AI Code Review

### 📌 Summary
{review.get("summary", "No summary provided.")}

---

### 🐛 Bugs
"""

    bugs = review.get("bugs", [])
    if bugs:
        for b in bugs:
            md += f"- {b}\n"
    else:
        md += "- No bugs found\n"

    md += "\n---\n### ⚡ Optimizations\n"

    opts = review.get("optimizations", [])
    if opts:
        for o in opts:
            md += f"- {o}\n"
    else:
        md += "- No optimizations suggested\n"

    md += "\n---\n### 🛠 Recommended Fixes\n"

    fixes = review.get("recommended_fixes", [])
    if fixes:
        for f in fixes:
            md += f"- {f}\n"
    else:
        md += "- No fixes required\n"

    md += f"""

---

### 🚦 Severity
**{severity}**

*Automated review generated by AI*
"""

    return md


def post_pr_comment(pr_url: str, review: Dict) -> Dict:
    """
    Post a comment to GitHub Pull Request (Conversation tab).
    """

    token = os.getenv("GITHUB_TOKEN")
    if not token:
        return {"success": False, "error": "GITHUB_TOKEN not set"}

    parsed = urlparse(pr_url)
    owner, repo, _, pr_number = parsed.path.strip("/").split("/")

    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }

    body = build_markdown(review)

    response = requests.post(
        url,
        headers=headers,
        json={"body": body},
        timeout=20
    )

    if response.status_code in (200, 201):
        return {"success": True}

    return {
        "success": False,
        "error": f"GitHub API error {response.status_code}: {response.text}"
    }
